apiVersion: v1
kind: Service
metadata:
  name: config-service
  labels:
    run: config-server
spec:
  ports:
    - name: port2
      protocol: TCP
      port: 8888
      nodePort: 30222
  selector:
    run: config-service
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: config-service
  labels:
    run: config-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: config-service
    spec:
      containers:
      - name: config-service
        image: art.local:8081/docker/notebook-k8s/config-service:latest
        env:
          - name: ZIPKIN_SERVER
            value: "192.168.99.100"
          - name: DISCOVERY_SERVICE_PORT
            value: "8761"
        ports:
        - containerPort: 8888
          protocol: TCP
      imagePullSecrets:
      - name: regcred-local
